FROM docker.io/library/alpine:${com.io7m.oci.versionAlpine}
FROM docker.io/library/eclipse-temurin:${com.io7m.oci.versionTemurin}

ENV PATH="/sbin:/bin:/usr/sbin:/usr/bin:/opt/java/openjdk/bin"

COPY gtyrell/gtyrell /gtyrell

LABEL "org.opencontainers.image.authors"="Mark Raynsford"
LABEL "org.opencontainers.image.description"="Git mirroring tool"
LABEL "org.opencontainers.image.licenses"="ISC"
LABEL "org.opencontainers.image.source"="https://www.github.com/io7m/gtyrell"
LABEL "org.opencontainers.image.title"="Gtyrell"
LABEL "org.opencontainers.image.url"="https://www.io7m.com/software/gtyrell"
LABEL "org.opencontainers.image.version"="${project.version}"
LABEL "org.opencontainers.image.revision"="${buildNumber}"

RUN ["apk", "update"]
RUN ["apk", "add", "git"]

VOLUME "/gtyrell/etc"
VOLUME "/data"

CMD ["/opt/java/openjdk/bin/java", "-jar", "/gtyrell/bin/gtyrell.jar"]
